quitOnTopLevelReturn: true
notARepository: 'quit'
promptToReturnFromSubprocess: false

gui:
  showIcons: true

keybinding:
  files:
    commitChanges: 'こ'
    commitChangesWithEditor: 'c'
  commits:
    renameCommit: 'れ'
    renameCommitWithEditor: 'r'

customCommands:
  - key: 'I'
    command: "git rebase -i {{.SelectedLocalCommit.Sha}}^"
    context: 'commits'
    description: 'start interactive rebase'
    subprocess: true
